# config for yumi teleop client

debug: False
cams:
  'left': 
    'cid': 1
    'flip': True
  'right': 
    'cid': 2
    'flip': True
  'side': 
    'cid': 0 
    'flip': False
grippers: 'continuous' # either binary or continuous
