# config for yumi teleop client

debug: False
cams:
  'left':
    'topic_name': 'yumi_teleop/vision_left/image_raw'
    'flip': True
  'right':
    'topic_name': 'yumi_teleop/vision_right/image_raw'
    'flip': True
  'side':
    'topic_name': 'yumi_teleop/vision_ws/image_raw'
    'flip': False
grippers: 'continuous' # either binary or continuous
